project:
  type: website

website:
  title: "zztopia"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/neo451
# format:
#   html:
#     theme:
#       - minty
#       - brand
#     css: styles.css
format:
  html:
    theme:
      - default
      - brand
    toc: true
    respect-user-color-scheme: true
    code-overflow: scroll
