project:
  type: website

website:
  title: "zztopia"
  site-url: https://neo451.github.io/blog/
  description: "Where I rant about tech and pop culture stuff"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/neo451
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      - default
      - brand
    toc: true
    respect-user-color-scheme: true
    code-overflow: scroll
